services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
  migration:
    image: back
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file: ".env"
    command: ["python", "manage.py", "migrate", "--noinput"]
  back_tests:
    image: back
    depends_on:
      migration:
        condition: service_completed_successfully
    env_file: '.env'
    command: ['./manage.py', 'test']
  web:
    image: back
    depends_on:
#      postgres:
#        condition: service_healthy
#        restart: true
#      migration:
#        condition: service_started
      back_tests:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    env_file: '.env'
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
